mariadb:
  image: mariadb:10.1
  container_name: mariadb
  ports:
    - 3306:3306
  volumes:
    - $PWD/database:/docker-entrypoint-initdb.d
  environment:
    - MYSQL_ROOT_PASSWORD=mypass
    - MYSQL_USER=admin
    - MYSQL_PASSWORD=mypass

phpmyadmin:
  image: phpmyadmin/phpmyadmin
  container_name: phpmyadmin
  ports:
    - 8080:80
  links:
    - mariadb:db
  environment:
    - MYSQL_ROOT_PASSWORD:mypass
    - MYSQL_USER=admin
    - MYSQL_PASSWORD=mypass

php:
  image: php:5.6.26-apache
  container_name: php-apache
  ports:
    - 80:80
  volumes:
    - $PWD/htdocs:/var/www/html
  links:
    - mariadb:mysql
