<?php
/**
 * Created by PhpStorm.
 * User: Leo
 * Date: 10.10.2016
 * Time: 12:47
 */
echo file_get_contents("./Views/index/includes/modalregister.html.php");
?>

<div class="container">
    <div id="loginbox" style="margin-top:50px;" class="mainbox col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2">
        <div class="panel panel-info" >
            <div class="panel-heading">
                <div class="panel-title" id="hallo">Login</div>
            </div>

            <div style="padding-top:30px" class="panel-body" >

                <div style="display:none" id="login-alert" class="alert alert-danger col-sm-12"></div>

                <form id="loginform" class="form-horizontal" role="form">
                    <div id="colloginuser" style="margin-bottom: 25px">
                    <div class="input-group" id="usernamelogingroup">
                        <span class="input-group-addon"><i class="fa fa-user fa"></i></span>
                        <input id="login-username" type="text" class="form-control" name="username" value="" placeholder="username">
                    </div>
                    </div>
                    <div id="colpasswordlogin" style="margin-bottom: 25px">
                    <div  class="input-group" id="passwordlogingroup">
                        <span class="input-group-addon"><i class="fa fa-lock fa-lg"></i></span>
                        <input id="login-password" type="password" class="form-control" name="password" placeholder="password">
                    </div>
                    </div>
                    <div style="margin-top:10px" class="form-group">
                        <!-- Button -->

                        <div class="col-sm-12 controls">
                            <a id="btn-loginpage" href="#" class="btn btn-success">Login  </a>
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-md-12 control">
                            <div style="border-top: 1px solid#888; padding-top:15px; font-size:85%" >
                                Don't have an account!
                                <a href="#" id="newDataModal">
                                    Register Here
                                </a>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
