
<?php
use Mvc\Library\AppTexts;
$text = new AppTexts();
    if (isset($_SESSION['userid'])){
        include("./views/index/includes/modalsensor.html.php");
        include("./views/index/includes/modalinfos.html.php");
        ?>
        <div class="container-fluid">
            <div class="row">

                <div class="col-md-3">
                    <ul class="nav nav-pills nav-stacked">
                        <?php
                        if ($this->vars->site == "home"){ ?>
                            <li class="active"><a href="/index/showLogin?site=home"><i class="fa fa-home fa-fw"></i><?php if ($_SESSION['language'] == "de") {
                                        echo $text->home;
                                    } else {
                                        echo $text->homeEN; }  ?></a></li>
                        <?php }
                        else { ?>
                            <li><a href="/index/showLogin?site=home"><i class="fa fa-home fa-fw"></i><?php if ($_SESSION['language'] == "de") {
                                        echo $text->home;
                                    } else {
                                        echo $text->homeEN; }  ?></a></li>
                        <?php }
                        if ($this->vars->site == "table"){ ?>
                            <li class="active"><a href="/index/showLogin?site=table"><i class="fa fa-cube fa-fw"></i><?php if ($_SESSION['language'] == "de") {
                                        echo $text->sensors;
                                    } else {
                                        echo $text->sensorsEN; }  ?></a></li>
                        <?php }
                        else { ?>
                            <li><a href="/index/showLogin?site=table"><i class="fa fa-cube fa-fw"></i><?php if ($_SESSION['language'] == "de") {
                                        echo $text->sensors;
                                    } else {
                                        echo $text->sensorsEN; }  ?></a></li>
                        <?php }
                        if ($this->vars->site == "settings"){ ?>
                            <li class="active"><a href="/index/showLogin?site=settings"><i class="fa fa-cogs fa-fw"></i><?php if ($_SESSION['language'] == "de") {
                                        echo $text->accsettings;
                                    } else {
                                        echo $text->accsettingsEN; }  ?></a></li>
                        <?php }
                        else { ?>
                            <li><a href="/index/showLogin?site=settings"><i class="fa fa-cogs fa-fw"></i><?php if ($_SESSION['language'] == "de") {
                                        echo $text->accsettings;
                                    } else {
                                        echo $text->accsettingsEN; }  ?></a></li>
                        <?php }
                        ?>
                        <li><a href="/index/logout"><i class="fa fa-sign-out fa-fw"></i><?php if ($_SESSION['language'] == "de") {
                                    echo $text->logout;
                                } else {
                                    echo $text->logoutEN; }  ?></a></li>
                    </ul>
                </div>
                <div class="col-md-9 well">
                    <div class="col-md-12 col-md-offset-1" style="margin-left:auto">
                        <?php include("./views/index/includes/".$this->vars->site.".html.php")?>
                    </div>
                </div>
            </div>
        </div>
     <?php }
     else {
          if ($_SESSION['language'] == "de") {
             echo $text->notloggedin;
         } else {
             echo $text->notloggedinEN; }
     }?>


<?php
include("./views/index/includes/footer.html.php");
?>