<?php
/**
 * Created by PhpStorm.
 * User: Leo
 * Date: 13.10.2016
 * Time: 08:08
 */

?>
<script src="/assets/jquery-1.10.2.js"></script>
<script src="/jQueryUI/v1_10_4/js/jquery-ui-1.10.4.custom.min.js"></script>
<link rel="stylesheet" href="/jQueryUI/v1_10_4/css/smoothness/jquery-ui-1.10.4.custom.css">
<link rel="stylesheet" href="/bootstrap/v3_3_7/css/bootstrap.min.css">
<link rel="stylesheet" href="/assets/font-awesome/4_4_0/css/font-awesome.css">
<script src="/bootstrap/v3_3_7/js/bootstrap.min.js"></script>
<link rel="stylesheet" href="/bootstrap/v3_3_7/table/v1_8_1/css/bootstrap-table.css">
<script src="/bootstrap/v3_3_7/table/v1_8_1/js/bootstrap-table.js"></script>
<script src="/bootstrap/v3_3_7/table/v1_8_1//js/extensions/export/bootstrap-table-export.js"></script>
<script src="/bootstrap/v3_3_7/table/tableExport/v0_0_0/tableExport.min.js"></script>
<script src="/bootstrap/v3_3_7/table/tableExport/v0_0_0/libs/FileSaver/FileSaver.min.js"></script>
<script src="/bootstrap/v3_3_7/table/v1_8_1//js/locale/bootstrap-table-de-DE.js"></script>

<link rel="stylesheet" href="/assets/flags/flags.css">
<link rel="stylesheet" href="/assets/default.css">
<script src="/assets/default.js"></script>